join:
  fields:
    source:
      required: true
      example: 192.168.1.10
      selector:
        text:
    members:
      required: true
      example: "[192.168.1.11]"
      selector:
        object:
    group_id:
      required: false
      selector:
        number:
          min: 1
          max: 255
    max_delay:
      required: false
      default: 5000
      selector:
        number:
          min: 0
          max: 10000
          unit_of_measurement: ms

unjoin:
  fields:
    source:
      required: true
      example: 192.168.1.10
      selector:
        text:

send_command:
  fields:
    host:
      required: true
      example: 192.168.1.10
      selector:
        text:
    commands:
      required: true
      example: '["SLI2B", "NSV0E0", "NLSI00001"]'
      selector:
        object:
    delay:
      required: false
      default: 2
      selector:
        number:
          min: 0
          max: 30
          step: 0.5
          unit_of_measurement: s
